name: quran_dev
description: "Aplikasi Al-Quran by Hadoy Dev."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  speech_to_text: ^6.6.0
  audioplayers: 6.6.0
  string_similarity: ^2.0.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/data
    - assets/data/112-al-ikhlash.json
    - assets/data/113-al-falaq.json
    - assets/data/114-an-nas.json
    # - assets/audio
    - assets/audio/112_Al-Ikhlas.mp3
    - assets/audio/112_Al-Ikhlas_01.mp3
    - assets/audio/112_Al-Ikhlas_02.mp3
    - assets/audio/112_Al-Ikhlas_03.mp3
    - assets/audio/112_Al-Ikhlas_04.mp3
    - assets/audio/113_Al-Falaq.mp3
    - assets/audio/113_Al-Falaq_01.mp3
    - assets/audio/113_Al-Falaq_02.mp3
    - assets/audio/113_Al-Falaq_03.mp3
    - assets/audio/113_Al-Falaq_04.mp3
    - assets/audio/113_Al-Falaq_05.mp3
    - assets/audio/114_An-Nas.mp3
    - assets/audio/114_An-Nas_01.mp3
    - assets/audio/114_An-Nas_02.mp3
    - assets/audio/114_An-Nas_03.mp3
    - assets/audio/114_An-Nas_04.mp3
    - assets/audio/114_An-Nas_05.mp3
    - assets/audio/114_An-Nas_06.mp3
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
